repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: pretty-format-json
    args: [--no-ensure-ascii, --autofix]
    files: |
      (?x)^(
        src/MCPServer/lib/assets/.*\.json|
        src/(MCPClient/MCPServer|dashboard)/osdeps/.*\.json
      )
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--safe, --quiet]
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    language_version: python3
