---
version: "2.1"

services:
  archivematica-tests:
    image: "archivematica-tests:latest"
    build:
      context: "../"
      dockerfile: "hack/Dockerfile"
      args:
        TARGET: "archivematica-tests"
        UBUNTU_VERSION: ${UBUNTU_VERSION:-18.04}
        UBUNTU_CODE: ${UBUNTU_CODE:-bionic}
    volumes:
      - "../:/src"
    links:
      - "mysql"
