---
name: "Acceptance Test"
on:
  pull_request:
    types: [labeled]
jobs:
  test:
    if: github.event.label.name == 'AMAUAT'
    name: "Test ${{ matrix.tag }}"
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        tag:
          - "aip-encrypt"
          - "aip-encrypt-mirror"
          - "black-box"
          - "mo-aip-reingest"
          - "tcc"
          - "tpc"
          - "uuids-dirs"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          submodules: true
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Build images"
        run: |
          make -C hack/ build
      - name: "Start services"
        run: |
          docker-compose up -d
        env:
          cluster.routing.allocation.disk.threshold_enabled: false
        working-directory: ./hack
      - name: "Wait for MySQL to start"
        run: |
          sleep 20
      - name: "Bootstrap services"
        run: |
          make -C hack/ bootstrap
      - name: "Restart services"
        run: |
          make -C hack/ restart-am-services
      - name: "Run AMAUAT tag"
        run: |
          make -C hack/ test-at-behave TAGS=${{ matrix.tag }}
