---
name: "Acceptance Test"
on:
  pull_request:
    types: [labeled]
jobs:
  test:
    if: github.event.label.name == 'AMAUAT'
    name: "Test ${{ matrix.tag }}"
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        tag:
          - "aip-encrypt"
          - "aip-encrypt-mirror"
          - "black-box"
          - "mo-aip-reingest"
          - "tcc"
          - "tpc"
          - "uuids-dirs"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          submodules: true
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@v1"
        id: buildx
        with:
          install: true
      - name: "Set up docker cache"
        uses: "actions/cache@v2"
        with:
          path: /tmp/.docker-cache-old
          key: ${{ runner.os }}-docker-${{ hashFiles('hack/**/Dockerfile') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ hashFiles('hack/**/Dockerfile') }}-
            ${{ runner.os }}-docker-
      - name: "Build archivematica-dashboard image"
        uses: "docker/build-push-action@v2"
        with:
          context: .
          file: ./hack/Dockerfile
          target: archivematica-dashboard
          tags: archivematica-dashboard:latest
          push: false
          load: true
          cache-from: type=local,src=/tmp/.docker-cache-old
          cache-to: type=local,dest=/tmp/.docker-cache-new,mode=max
      - name: "Build archivematica-mcp-server image"
        uses: "docker/build-push-action@v2"
        with:
          context: .
          file: ./hack/Dockerfile
          target: archivematica-mcp-server
          tags: archivematica-mcp-server:latest
          push: false
          load: true
          cache-from: type=local,src=/tmp/.docker-cache-old
          cache-to: type=local,dest=/tmp/.docker-cache-new,mode=max
      - name: "Build archivematica-mcp-client image"
        uses: "docker/build-push-action@v2"
        with:
          context: .
          file: ./hack/Dockerfile
          target: archivematica-mcp-client
          tags: archivematica-mcp-client:latest
          push: false
          load: true
          cache-from: type=local,src=/tmp/.docker-cache-old
          cache-to: type=local,dest=/tmp/.docker-cache-new,mode=max
      - name: "Build archivematica-storage-service image"
        uses: "docker/build-push-action@v2"
        with:
          context: ./hack/submodules/archivematica-storage-service
          file: ./hack/submodules/archivematica-storage-service/Dockerfile
          tags: archivematica-storage-service:latest
          push: false
          load: true
          cache-from: type=local,src=/tmp/.docker-cache-old
          cache-to: type=local,dest=/tmp/.docker-cache-new,mode=max
      - name: "Build archivematica-acceptance-tests image"
        uses: "docker/build-push-action@v2"
        with:
          context: ./hack/submodules/archivematica-acceptance-tests
          file: ./hack/submodules/archivematica-acceptance-tests/Dockerfile
          tags: archivematica-acceptance-tests:latest
          push: false
          load: true
          cache-from: type=local,src=/tmp/.docker-cache-old
          cache-to: type=local,dest=/tmp/.docker-cache-new,mode=max
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Build images"
        run: |
          make -C hack/ build
      - name: "Start services"
        run: |
          docker-compose up -d
        env:
          cluster.routing.allocation.disk.threshold_enabled: false
        working-directory: ./hack
      - name: "Wait for MySQL to start"
        run: |
          sleep 20
      - name: "Bootstrap services"
        run: |
          make -C hack/ bootstrap
      - name: "Restart services"
        run: |
          make -C hack/ restart-am-services
      - name: "Run AMAUAT tag"
        run: |
          make -C hack/ test-at-behave TAGS=${{ matrix.tag }}
      - name: "Set newest docker cache"
        run: |
          rm -rf /tmp/.docker-cache-old
          mv /tmp/.docker-cache-new /tmp/.docker-cache-old
