---
name: "Acceptance Test"
on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - "dev/drop-py27"
jobs:
  test:
    name: "Test ${{ matrix.tag }} on ${{ matrix.python_version }} and ${{ matrix.browser }}"
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "aip-encrypt"
          - "aip-encrypt-mirror"
          - "black-box"
          - "icc"
          - "ipc preservation"
          - "ipc access"
          - "mo-aip-reingest"
          - "tcc"
          - "tpc"
          - "uuids-dirs"
        browser:
          - "Firefox"
          - "Chrome"
        python_version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        exclude:
          - tag: "black-box"
            browser: Firefox
          - tag: "ipc preservation"
            browser: Firefox
          - tag: "ipc access"
            browser: Firefox
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          submodules: true
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Start MySQL"
        run: |
          docker-compose up -d mysql
        working-directory: ./hack
      - name: "Build images"
        run: |
          make -C hack/ build
        env:
          PYTHON_VERSION: ${{ matrix.python_version }}
      - name: "Start services"
        run: |
          docker-compose up -d
        env:
          cluster.routing.allocation.disk.threshold_enabled: false
          PYTHON_VERSION: ${{ matrix.python_version }}
        working-directory: ./hack
      - name: "Bootstrap services"
        run: |
          make -C hack/ bootstrap
      - name: "Restart services"
        run: |
          make -C hack/ restart-am-services
      - name: "Run AMAUAT tag"
        run: |
          make -C hack/ test-at-behave TAGS="${{ matrix.tag }}" BROWSER=${{ matrix.browser }}
