---
name: "Acceptance Test"
on:
  push:
    branches:
      - "dev/py37"
jobs:
  test:
    name: "Test ${{ matrix.tag }} on ${{ matrix.browser }} on ${{ matrix.ubuntu.version }}"
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        ubuntu:
          - version: 18.04
            code: bionic
          # - version: 22.04
          #   code: jammy
        tag:
          - "aip-encrypt"
          - "aip-encrypt-mirror"
          - "black-box"
          - "icc"
          - "ipc preservation"
          - "ipc access"
          - "metadata-xml"
          - "tcc"
          - "tpc"
          - "uuids-dirs"
        browser:
          - "Firefox"
          - "Chrome"
        exclude:
          - tag: "black-box"
            browser: Firefox
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          submodules: true
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Start MySQL"
        run: |
          docker-compose up -d mysql
        working-directory: ./hack
      - name: "Build images"
        run: |
          make -C hack/ build
        env:
          UBUNTU_VERSION: ${{ matrix.ubuntu.version }}
          UBUNTU_CODE: ${{ matrix.ubuntu.code }}
      - name: "Start services"
        run: |
          docker-compose up -d
        env:
          cluster.routing.allocation.disk.threshold_enabled: false
          UBUNTU_VERSION: ${{ matrix.ubuntu.version }}
          UBUNTU_CODE: ${{ matrix.ubuntu.code }}
        working-directory: ./hack
      - name: "Bootstrap services"
        run: |
          make -C hack/ bootstrap
        env:
          UBUNTU_VERSION: ${{ matrix.ubuntu.version }}
          UBUNTU_CODE: ${{ matrix.ubuntu.code }}
      - name: "Restart services"
        run: |
          make -C hack/ restart-am-services
        env:
          UBUNTU_VERSION: ${{ matrix.ubuntu.version }}
          UBUNTU_CODE: ${{ matrix.ubuntu.code }}
      - name: "Run AMAUAT tag"
        run: |
          make -C hack/ test-at-behave TAGS="${{ matrix.tag }}" BROWSER=${{ matrix.browser }}
        env:
          UBUNTU_VERSION: ${{ matrix.ubuntu.version }}
          UBUNTU_CODE: ${{ matrix.ubuntu.code }}
