---
name: "Acceptance Tests"
on:
  # pull_request:
  #   types: [labeled]
  push:
    branches:
      - "dev/amauat-reusable-workflows"
jobs:
  aip-encrypt-firefox:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: aip-encrypt
      browser: Firefox
  aip-encrypt-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: aip-encrypt
      browser: Chrome
  aip-encrypt-mirror-firefox:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: aip-encrypt-mirror
      browser: Firefox
  aip-encrypt-mirror-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: aip-encrypt-mirror
      browser: Chrome
  black-box-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: black-box
      browser: Chrome
  icc-firefox:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: icc
      browser: Firefox
  icc-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: icc
      browser: Chrome
  ipc_preservation-firefox:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: ipc preservation
      browser: Firefox
  ipc_preservation-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: ipc preservation
      browser: Chrome
  ipc_access-firefox:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: ipc access
      browser: Firefox
  ipc_access-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: ipc access
      browser: Chrome
  mo-aip-reingest-firefox:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: mo-aip-reingest
      browser: Firefox
  mo-aip-reingest-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: mo-aip-reingest
      browser: Chrome
  tcc-firefox:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: tcc
      browser: Firefox
  tcc-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: tcc
      browser: Chrome
  tpc-firefox:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: tpc
      browser: Firefox
  tpc-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: tpc
      browser: Chrome
  uuids-dirs-firefox:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: uuids-dirs
      browser: Firefox
  uuids-dirs-chrome:
    # if: github.event.label.name == 'AMAUAT'
    uses: artefactual/archivematica/.github/workflows/acceptance-test-run.yml@dev/amauat-reusable-workflows
    with:
      tags: uuids-dirs
      browser: Chrome
