---
name: "Acceptance Test"
on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - "dev/amauat-coverage-report-take2"
jobs:
  test:
    name: "Test ${{ matrix.tag }} on ${{ matrix.browser }}"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "aip-encrypt"
          - "aip-encrypt-mirror"
          - "black-box"
          - "icc"
          - "ipc preservation"
          - "ipc access"
          - "metadata-xml"
          - "tcc"
          - "tpc"
          - "uuids-dirs"
        browser:
          - "Chrome"
        exclude:
          - tag: "black-box"
            browser: Firefox
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
        with:
          submodules: true
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Start MySQL"
        run: |
          docker compose up -d mysql
        working-directory: ./hack
      - name: "Build images"
        run: |
          make -C hack/ build
        env:
          PYTHON_VERSION: "3.9"
      - name: "Start services"
        run: |
          docker compose up -d
        env:
          ELASTICSEARCH_DISK_THRESHOLD_ENABLED: "false"
        working-directory: ./hack
      - name: "Bootstrap services"
        run: |
          make -C hack/ bootstrap
      - name: "Restart services"
        run: |
          make -C hack/ restart-am-services
      - name: "Run AMAUAT tag"
        id: "amauat-run"
        continue-on-error: true
        run: |
          make -C hack/ test-at-behave TAGS="${{ matrix.tag }}" BROWSER=${{ matrix.browser }}
      - name: "Save docker logs on failure"
        if: "${{ (failure() && steps.amauat-run.outcome == 'failure') || (cancelled() && steps.amauat-run.outcome == 'cancelled') }}"
        run: |
          mkdir docker-logs
          docker compose logs --no-log-prefix --no-color archivematica-mcp-server > docker-logs/mcp-server.log
          docker compose logs --no-log-prefix --no-color archivematica-mcp-client > docker-logs/mcp-client.log
          docker compose logs --no-log-prefix --no-color archivematica-dashboard > docker-logs/dashboard.log
          docker compose logs --no-log-prefix --no-color archivematica-storage-service > docker-logs/storage-service.log
        working-directory: ./hack
      - name: "Upload docker logs on failure"
        if: "${{ (failure() && steps.amauat-run.outcome == 'failure') || (cancelled() && steps.amauat-run.outcome == 'cancelled') }}"
        uses: "actions/upload-artifact@v4"
        with:
          name: "docker-logs-${{ matrix.tag }}-${{ matrix.browser }}"
          path: "./hack/docker-logs"
      - name: "Combine coverage report"
        working-directory: ./hack
        run: |
          ls -altr ../.coverage.*
          docker compose run --rm --no-deps --entrypoint coverage archivematica-mcp-server combine
          docker compose run --rm --no-deps --entrypoint coverage archivematica-mcp-server xml -o /src/coverage.xml
      - name: "Upload coverage report"
        uses: "codecov/codecov-action@v4"
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
          flags: "amauats,${{ matrix.tag }}"
          name: ${{ matrix.tag }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}